// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CancelAppleLogin(arg1:string):Promise<void>;

export function CancelJob(arg1:string):Promise<void>;

export function CheckEnvironment():Promise<main.EnvironmentStatus>;

export function GetAppleAccountStatus():Promise<main.AppleAccountStatus>;

export function ImportIPA(arg1:string):Promise<main.AppView>;

export function InstallApp(arg1:string,arg2:string):Promise<main.JobHandle>;

export function ListAuditEvents(arg1:number):Promise<Array<main.AuditEvent>>;

export function ListDevices():Promise<Array<main.Device>>;

export function ListManagedApps(arg1:string):Promise<Array<main.AppView>>;

export function ListSigningIdentities():Promise<Array<main.SigningIdentityOption>>;

export function RememberAppleCredentials(arg1:string,arg2:string):Promise<void>;

export function RememberedAppleCredentials():Promise<main.RememberedAppleCredentials>;

export function RenewApp(arg1:string,arg2:string,arg3:string):Promise<main.JobHandle>;

export function ResendTwoFactor(arg1:string):Promise<void>;

export function RevealSignedIPA(arg1:string):Promise<void>;

export function SelectAndImportIPA():Promise<main.AppView>;

export function SelectDeveloperTeam(arg1:string):Promise<void>;

export function SelectSigningIdentity(arg1:string):Promise<void>;

export function SignApp(arg1:string,arg2:string,arg3:string,arg4:string):Promise<main.JobHandle>;

export function SignOutAppleAccount():Promise<void>;

export function StartAppleLogin(arg1:string,arg2:string):Promise<main.LoginChallenge>;

export function SubmitTwoFactor(arg1:string,arg2:string):Promise<main.AppleAccountStatus>;
