// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelAppleLogin(arg1) {
  return window['go']['main']['App']['CancelAppleLogin'](arg1);
}

export function CancelJob(arg1) {
  return window['go']['main']['App']['CancelJob'](arg1);
}

export function CheckEnvironment() {
  return window['go']['main']['App']['CheckEnvironment']();
}

export function GetAppleAccountStatus() {
  return window['go']['main']['App']['GetAppleAccountStatus']();
}

export function ImportIPA(arg1) {
  return window['go']['main']['App']['ImportIPA'](arg1);
}

export function InstallApp(arg1, arg2) {
  return window['go']['main']['App']['InstallApp'](arg1, arg2);
}

export function ListAuditEvents(arg1) {
  return window['go']['main']['App']['ListAuditEvents'](arg1);
}

export function ListDevices() {
  return window['go']['main']['App']['ListDevices']();
}

export function ListManagedApps(arg1) {
  return window['go']['main']['App']['ListManagedApps'](arg1);
}

export function ListSigningIdentities() {
  return window['go']['main']['App']['ListSigningIdentities']();
}

export function RememberAppleCredentials(arg1, arg2) {
  return window['go']['main']['App']['RememberAppleCredentials'](arg1, arg2);
}

export function RememberedAppleCredentials() {
  return window['go']['main']['App']['RememberedAppleCredentials']();
}

export function RenewApp(arg1, arg2, arg3) {
  return window['go']['main']['App']['RenewApp'](arg1, arg2, arg3);
}

export function ResendTwoFactor(arg1) {
  return window['go']['main']['App']['ResendTwoFactor'](arg1);
}

export function RevealSignedIPA(arg1) {
  return window['go']['main']['App']['RevealSignedIPA'](arg1);
}

export function SelectAndImportIPA() {
  return window['go']['main']['App']['SelectAndImportIPA']();
}

export function SelectDeveloperTeam(arg1) {
  return window['go']['main']['App']['SelectDeveloperTeam'](arg1);
}

export function SelectSigningIdentity(arg1) {
  return window['go']['main']['App']['SelectSigningIdentity'](arg1);
}

export function SignApp(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SignApp'](arg1, arg2, arg3, arg4);
}

export function SignOutAppleAccount() {
  return window['go']['main']['App']['SignOutAppleAccount']();
}

export function StartAppleLogin(arg1, arg2) {
  return window['go']['main']['App']['StartAppleLogin'](arg1, arg2);
}

export function SubmitTwoFactor(arg1, arg2) {
  return window['go']['main']['App']['SubmitTwoFactor'](arg1, arg2);
}
